name: crypto_currencies_test_app
description: "Test app for the crypto company"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # http client
  dio: ^5.4.3+1
  # (optional) but useful
  pretty_dio_logger: ^1.3.1

  # arch
  flutter_bloc: ^8.1.5
  logging: ^1.2.0

  # Environment, flavors
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5

  # Utilities
  # (optional) very useful for formatting numbers and dates
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/sf_pro_text/SF-Pro-Text-Semibold.otf
          weight: 600
        # TODO: Add more variants if need  
        
  assets:
    - .env

  uses-material-design: true  
